//! perspicax's own Wayland protocols, for the server and the client side.
//!
//! One so far: `perspicax-shell-v1`, the channel between the compositor and
//! `perspicax-shell` (see `protocols/perspicax-shell-v1.xml`). It carries
//! only what no standard protocol does: that the person asked for a menu,
//! that the config changed, that the session should end, from version 2
//! the keyboard's layouts and which is in use, and from version 3 that the
//! person asked for a pie. The shell's
//! surfaces, taskbar and pager all speak standard protocols, so any piece of
//! it can be replaced by a program that knows nothing of this one.
//!
//! The bindings are generated by `wayland-scanner`, as `wayland-protocols`
//! generates the standard ones: the `server` feature for the compositor,
//! `client` for the shell. A crate of its own so that both sides compile
//! the same XML, and neither has to depend on the other.

#![cfg_attr(docsrs, feature(doc_cfg))]

/// `perspicax-shell-v1`: menus and pies asked for, a config changed, a
/// session ended, the keyboard's layouts.
pub mod shell {
    /// `perspicax_shell_v1`, whose interface is at version 3.
    pub mod v1 {
        #[cfg(feature = "client")]
        pub use self::generated::client;
        #[cfg(feature = "server")]
        pub use self::generated::server;

        // The scanner's macros read the XML without telling cargo, so an
        // edit to it alone would not rebuild this crate. Reading it here
        // does: rustc records what `include_str!` reads.
        const _: &str = include_str!("../protocols/perspicax-shell-v1.xml");

        // The scanner's output, as `wayland-protocols` includes its own.
        // The interface tables it emits for libwayland are statics holding
        // raw pointers, declared `unsafe impl Sync` and read through
        // `unsafe { &... }`: generated, never written by hand, and the
        // reason this crate holds `deny` rather than the workspace's
        // `forbid`.
        #[allow(
            unsafe_code,
            reason = "wayland-scanner's interface tables are raw-pointer statics"
        )]
        mod generated {
            #![allow(
                dead_code,
                non_camel_case_types,
                unused_unsafe,
                unused_variables,
                non_upper_case_globals,
                non_snake_case,
                unused_imports,
                missing_docs,
                clippy::all,
                reason = "generated by wayland-scanner"
            )]

            #[cfg(feature = "client")]
            pub mod client {
                //! The shell's side.
                use wayland_client;
                use wayland_client::protocol::*;

                pub mod __interfaces {
                    use wayland_client::protocol::__interfaces::*;
                    wayland_scanner::generate_interfaces!("protocols/perspicax-shell-v1.xml");
                }
                use self::__interfaces::*;

                wayland_scanner::generate_client_code!("protocols/perspicax-shell-v1.xml");
            }

            #[cfg(feature = "server")]
            pub mod server {
                //! The compositor's side.
                use wayland_server;
                use wayland_server::protocol::*;

                pub mod __interfaces {
                    use wayland_server::protocol::__interfaces::*;
                    wayland_scanner::generate_interfaces!("protocols/perspicax-shell-v1.xml");
                }
                use self::__interfaces::*;

                wayland_scanner::generate_server_code!("protocols/perspicax-shell-v1.xml");
            }
        }
    }
}
